version: "3.7"
services:
  sql-server-db:
    container_name: nimble2021
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "2433:2433"
    environment:
      SA_PASSWORD: "super_duper_password"
      ACCEPT_EULA: "Y" 
